# MultiBundles - Shopify Bundler App

scopes = "read_products,write_products,read_inventory,write_inventory,read_orders,read_markets,write_markets"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/subscriptions_update"
  topics = ["app_subscriptions/update"]

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = ["inventory_levels/update"]
  uri = "/webhooks/inventory/update"

  # Mandatory compliance webhooks for public apps
  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = ["shop/redact"]
