api_version = "2025-10"

[[extensions]]

uid = "a9fa67e8-f94c-f93e-02eb-dd121b88d916c46afc01"

type = "theme"
name = "MultiBundles Theme Extension"
handle = "multibundles-theme"

  [extensions.settings]
  [[extensions.settings.attributes]]
  type = "text"
  key = "app_name"
  [extensions.settings.attributes.label]
  en = "App Name"
  default = "MultiBundles"
